# Se recomienda usar siempre la última version de docker compose
version: '3'
# 
services:
    # Nuestro primer servicio se llamará `db`
    db:
        # https://docs.docker.com/compose/compose-file/
        container_name: mysql
        ports:
            - "3306:3306"
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=12345678"